config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

     ###    ########  ##     ## #### ##    ##
    ## ##   ##     ## ###   ###  ##  ###   ##
   ##   ##  ##     ## #### ####  ##  ####  ##
  ##     ## ##     ## ## ### ##  ##  ## ## ##
  ######### ##     ## ##     ##  ##  ##  ####
  ##     ## ##     ## ##     ##  ##  ##   ###
  ##     ## ########  ##     ## #### ##    ##

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :activities, only: [:index]
    resources :users, only: [:index, :show]
  end

  get 'pages/index'
  get 'pages/get'
  get 'pages/readme'

  resources :users, only: [] do
    resources :reviews, controller: :user_reviews
  end
  resources :reviews

  root 'pages#index'
end

app/views/layouts/_alerts.haml
- unless notice == nil || notice == ''
  .alert.alert-success.text-center
    .container.text-center
      = notice
- unless alert == nil || alert == ''
  .alert.alert-danger.text-center
    .container.text-center
      = alert

app/views/layouts/_alerts.html.haml
- unless notice == nil || notice == ''
  .alert.alert-success.text-center
    .container.text-center
      = notice
- unless alert == nil || alert == ''
  .alert.alert-danger.text-center
    .container.text-center
      = alert

app/views/layouts/_footer.html.haml
%footer
  .container
    = link_to 'FAQ', '#'
    = link_to 'Contact', '#'
    = link_to 'Partner With Us', '#'
    = link_to 'Sign In', new_user_session_path unless current_user

app/views/layouts/_google_analytics.html.haml
%script{async: '', :src => "https://www.googletagmanager.com/gtag/js?id=#{ENV['GOOGLE_ANALYTICS_KEY']}"}
%script
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  google_analytics_key = "#{ENV['GOOGLE_ANALYTICS_KEY']}";

  gtag('config', google_analytics_key);

app/views/layouts/_intercom.html.haml
:javascript
  window.intercomSettings = {
    app_id: "#{ENV['INTERCOM_APP_ID']}"
  };

  (function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/"#{ENV['INTERCOM_APP_ID']}"';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  %button.navbar-toggler.navbar-toggler-right{ aria: { expanded: 'false', label: 'Toggle Navigation' }, data: { target: '#navbarSupportedContent', toggle: 'collapse' }, type: 'button' }
    %span.navbar-toggler-icon
  = link_to root_url, class: 'navbar-brand' do
    Home

  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        = link_to pages_get_path, class: 'nav-link' do
          Get
      %li.nav-item
        = link_to pages_readme_path, class: 'nav-link' do
          ReadMe
      %li.nav-item
        = link_to reviews_path, class: 'nav-link' do
          Reviews
      - if current_user && current_user.is_admin
        = link_to admin_dashboard_path, class: 'nav-link' do
          Admin Dashboard
    %ul.navbar-nav.navbar-right
      - if current_user
        %li.nav-profile-pic
          = image_tag(current_user.featured_image_url(:thumb))
        %li.dropdown.nav-link
          #navigation-user-settings.dropdown-toggle{ aria: { expanded: 'false', haspopup: 'true' }, data: { toggle: 'dropdown' } }
            .fa.fa-cog
            %span.caret
          .dropdown-menu.dropdown-menu-right{ aria: { labelledby: 'navigation-user-settings' } }
            = link_to edit_user_registration_url, class: 'nav-link' do
              Settings
            = link_to destroy_user_session_url, method: :delete, class: 'nav-link' do
              Logout
            %ul.dropdown-menu.user-menu
              %li
                = link_to 'Account Settings', edit_user_registration_path
              %li
                = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link'
      - else
        %li.nav-item
          = link_to 'Sign In', new_user_session_url, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', http: {equiv: 'Content-Type'} }
    %title RailsAppTemplate

    = csrf_meta_tags
    = display_meta_tags og: {site: @meta_site_name, title: "#{@meta_title} | #{@meta_subtitle}", description: @meta_description, keywords: @meta_keywords, type: @meta_type, :url => request.original_url, prev: "#{request.referer}", image: @meta_image}

    = javascript_include_tag 'application'

    %link{crossorigin: 'anonymous', href: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css', integrity: 'sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ', rel: 'stylesheet'}/
    %script{crossorigin: 'anonymous', integrity: 'sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n', src: 'https://code.jquery.com/jquery-3.1.1.slim.min.js'}
    %script{crossorigin: 'anonymous', integrity: 'sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb', src: 'https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js'}
    %script{crossorigin: 'anonymous', integrity: 'sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn', src: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js'}

    = stylesheet_link_tag 'application', media: 'all'

  %body
    = render 'layouts/alerts'
    = render 'layouts/navigation'

    .container
      = yield

    = render 'layouts/footer'
    = render 'layouts/intercom'
    = render 'layouts/google_analytics'